import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

export default function Home() {

    return (
      <div className='{styles.container}'>

         <Head>
          <title>Kizukuと愉快な仲間たち</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> 

        <Link href="/rooms">
            <p>ルーム一覧</p>
        </Link>

        <main className='{styles.main}'>

          <h1 className="text-orange-500 text-3xl font-bold underline">
            this is tailwind
          </h1>

          <h1 className="text-cyan-500 text-3xl font-bold underline">
            this is naka no branch
          </h1>
        
          <div className="content">

            <div className="right">
              <div className="door"></div>
            </div>

            <div className="left">

              <div className="stairs">
                <div className="bars"></div>
              </div>

              <div className="nosferatu"></div>

            </div>

            <div className='cinema'>
              <div className="effect">
                <div className="grain"></div>
              </div>
            </div>

          </div>
        
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2 className='text-white'>
              Deploy &rarr;
            </h2>

            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
            
          </a>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}