import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/rooms.module.css'
import { useRef, useEffect, useState } from 'react'

export default function Home() {

    const socketRef = useRef<WebSocket>()
    const [isConnected, setIsConnected] = useState(false)
    
    useEffect(() => {
      // socketRef.current = new WebSocket('ws://localhost:8080/ws/123?v=1.0')
      socketRef.current = new WebSocket('wss://hajimete-hackathon-2022.onrender.com/ws/123?v=1.0')

      console.log(socketRef)
      socketRef.current.onopen = function () {
        setIsConnected(true)
        console.log('Connected')
      }
    
      socketRef.current.onclose = function () {
        console.log('closed')
        setIsConnected(false)
      }
    }, [])
    
    return (
      <div className='{styles.container}'>

        <Head>
          <title>Kizukuと愉快な仲間たち</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className='{styles.main}'>

          <a>
            WebSocket is connected : {`${isConnected}`}
          </a>

          <Link href="/">
            <p>トップページ</p>
          </Link>

        </main>
        
      </div>
    )
    
}